[TODO] 🐳 Dockerfile: 需要解决挂载的工作目录的权限问题，目前挂载的目录权限是 root，不是ubuntu

diff --git a/dockerfiles/Dockerfile.user-ubuntu b/dockerfiles/Dockerfile.user-ubuntu
--- a/dockerfiles/Dockerfile.user-ubuntu
+++ b/dockerfiles/Dockerfile.user-ubuntu
@@ -37,7 +37,6 @@ ENV DEBIAN_FRONTEND=noninteractive
 
 # set -x 选项会使得每个命令在执行前都会被打印出来，报错时会显示是哪个命令出错
 RUN set -x && \
-    sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' ${HOME}/.bashrc && \
     APT_DEB822_FILE="/etc/apt/sources.list.d/ubuntu.sources" && \
     sed -i "s#//.*archive.ubuntu.com#//${MIRRORS_URL}#g" ${APT_DEB822_FILE} && \
     sed -i "s#//ports.ubuntu.com#//${MIRRORS_URL}#g" ${APT_DEB822_FILE} && \
@@ -53,28 +52,60 @@ RUN set -x && \
 
 ENV LANG=zh_CN.utf8
 
-ARG USER_NAME="root"
-ARG USER_HOME="/${USER_NAME}"
+
+# ============================================================
+#   设置用户
+# ============================================================
+# 添加用户
+ARG USER_NAME="ubuntu"
+ARG USER_HOME="/home/${USER_NAME}"
+# ARG USER_SHELL="/bin/bash"
+# ARG USER_ID="1000"
+# ARG USER_GROUP="ubuntu"
+# ARG USER_GROUP_ID="1000"
+# ARG USER_PASSWORD="ubuntu"
+# RUN set -x && \
+#     groupadd -g ${USER_GROUP_ID} ${USER_GROUP} && \
+#     useradd -m -u ${USER_ID} -g ${USER_GROUP_ID} -s ${USER_SHELL} ${USER_NAME} && \
+#     echo "${USER_NAME}:${USER_PASSWORD}" | chpasswd && \
+#     usermod -aG sudo ${USER_NAME} && \
+#     echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
+
+# 删除该用户的密码
+RUN passwd -d ${USER_NAME}
+# 切换到 ubuntu 用户
+USER ${USER_NAME}
+# #force_color_prompt=yes 取消注释，使得终端提示符有颜色
+RUN sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' ${USER_HOME}/.bashrc
 
 # ============================================================
 #   Python 环境
 # ============================================================
+# 切换为 bash 才有 source 命令，否则无法激活虚拟环境
+# SHELL [ "/bin/bash", "-c" ]
 # # PEP 668 – Python base environments Python 增强提案 (PEP)：https://realpython.com/python-virtual-environments-a-primer/?ref=yaolong.net
 # # https://www.adamsdesk.com/posts/resolve-pip-externally-managed-environment
 # # 临时解决方案  --ignoreExternallyManagedEnvironment
-ADD . $USER_HOME/tmp
-ENV PYTHON_VENV_DIR=$USER_HOME/.venv
-ENV PIP_MIRROR="https://mirrors.ustc.edu.cn/pypi/simple"
-RUN set -x && \
-    python3 -m venv ${PYTHON_VENV_DIR} --clear && \
-    echo "source ${PYTHON_VENV_DIR}/bin/activate" >> $USER_HOME/.bashrc && \
-    VENV_PYTHON=${PYTHON_VENV_DIR}/bin/python3 && \
-    $VENV_PYTHON -m pip install -i $PIP_MIRROR -U --upgrade pip setuptools wheel && \
-    $VENV_PYTHON -m pip config set global.index-url $PIP_MIRROR && \
-    [ -f $USER_HOME/tmp/requirements.txt ] && $VENV_PYTHON -m pip install -r ${USER_HOME}/tmp/requirements.txt || echo "requirements.txt not found, skip install" && \
-    sudo rm -rf $USER_HOME/tmp && \
-    # 清理缓存，缓存目录： - Linux: ~/.cache/pip and ~/.cache/pipenv  - macOS: ~/Library/Caches/pip and ~/.cache/pipenv  - Windows: %LocalAppData%/pip/Cache
-    $VENV_PYTHON -m pip cache purge
-
+# ADD . ${USER_HOME}/tmp
+# ENV PYTHON_VENV_DIR=$USER_HOME/.venv
+# ENV PIP_MIRROR="https://mirrors.ustc.edu.cn/pypi/simple"
+# RUN set -x && \
+#     python3 -m venv ${PYTHON_VENV_DIR} --clear && \
+#     source ${PYTHON_VENV_DIR}/bin/activate && \
+#     python3 -m pip install -i $PIP_MIRROR -U --upgrade pip setuptools wheel && \
+#     python3 -m pip config set global.index-url $PIP_MIRROR && \
+#     [[ -f ${USER_HOME}/tmp/requirements.txt ]] && python3 -m pip install -r ${USER_HOME}/tmp/requirements.txt || echo "requirements.txt not found, skip install" && \
+#     sudo rm -rf ${USER_HOME}/tmp && \
+#     # 清理缓存，缓存目录： - Linux: ~/.cache/pip and ~/.cache/pipenv  - macOS: ~/Library/Caches/pip and ~/.cache/pipenv  - Windows: %LocalAppData%/pip/Cache
+#     python3 -m pip cache purge
+    
 # 提升虚拟环境 python 的优先级
-ENV PATH=${PYTHON_VENV_DIR}/bin:$PATH
+# ENV PATH=${PYTHON_VENV_DIR}/bin:$PATH
+
+# ============================================================
+#   为了下一次重复构建，切换回 root 用户
+# ============================================================
+USER root
+
+# CMD [ "cat", "/etc/os-release" ]
+# CMD [ "uname", "-m" ]
